Auto Commit of Application List for Desktop

diff --git a/bin/rsync-desktop b/bin/rsync-desktop
--- a/bin/rsync-desktop
+++ b/bin/rsync-desktop
@@ -1,3 +1,5 @@
 #!/bin/bash
 #Automated .sh file for rsync backups to Synology NAS.
-rsync -a -e 'ssh -p 2023' --delete --info=progress2  --exclude={"/.thumbnails/","/Downloads","/Google_Drive","/.cache/google-chrome","/.local/share/Trash/","/CloudStation/","/android-sdk-linux","/kernel_build","/android_devices"} /home/ridobe/ ridobe@50.90.73.229:/volume1/homes/ridobe/rsync_ridobe_desktop/home/ 
+LOG=~/crontab_log/rsync-desktop.log 2>&1
+echo "*** $(date -R) ***" >> $LOG
+rsync -a -e "ssh -p 2023 -i /home/ridobe/.ssh/id_rsa" --delete --info=progress2  --exclude={"/.thumbnails/","/Downloads","/Google_Drive","/.cache/google-chrome","/.local/share/Trash/","/CloudStation/","/android-sdk-linux","/kernel_build","/android_devices"} /home/ridobe/ ridobe@50.90.73.229:/volume1/homes/ridobe/rsync_ridobe_desktop/home/ && echo "Successfully completed" >> $LOG || echo "Error. Try again" >> $LOG
diff --git a/bin/update_app_list_Desktop b/bin/update_app_list_Desktop
--- a/bin/update_app_list_Desktop
+++ b/bin/update_app_list_Desktop
@@ -1,4 +1,4 @@
 #!/bin/bash
-LOG=/var/log/desktop-to-git.log
+LOG=~/crontab_log/rsync-desktop.log 2>&1
 echo "*** $(date -R) ***" >> $LOG
-cd $HOME/dotfiles && bin/saveApps desktop --quite && git add custom/desktop.list && git commit -m 'Auto Commit of Application List for Desktop' && git push
+cd $HOME/dotfiles && bin/saveApps desktop --quite && git add * && git commit -m 'Auto Commit of Application List for Desktop' && git push && echo "Successfully completed" >> $LOG || echo "Error. Try again" >> $LOG
