corrected mistakes for rsync

diff --git a/bin/rsync-archpad b/bin/rsync-archpad
--- a/bin/rsync-archpad
+++ b/bin/rsync-archpad
@@ -1,5 +1,5 @@
 #!/bin/bash
 #Automated .sh file for rsync backups to Synology NAS.
-LOG=~/crontab_log/rsync-chromebook.log 2>&1
+LOG=~/crontab_log/rsync-archpad.log 2>&1
 echo "*** $(date -R) ***" >> $LOG
-rsync -a -e 'ssh -p 2023' --delete --info=progress2  --exclude={"/.thumbnails/","/Downloads","/Google_Drive","/.cache/google-chrome","/.local/share/Trash/","/CloudStation/","/android-sdk-linux","/kernel_build","/android_devices"} /home/ridobe/ ridobe@50.90.45.152:/volume1/homes/ridobe/rsync_ridobe_archpad/home/ && echo "Successfully completed" >> $LOG || echo "Error. Try again" >> $LOG
+rsync -a -e 'ssh -p 2023' --delete --info=progress2  --exclude={"/.thumbnails/","/Downloads","/Google_Drive","/.cache/google-chrome","/.local/share/Trash/","/CloudStation/","/kernel_build","/android_devices"} /home/ridobe/ ridobe@50.90.45.152:/volume1/homes/ridobe/rsync_ridobe_thinkpad/home/ && echo "Successfully completed" >> $LOG || echo "Error. Try again" >> $LOG
